### ISSUE TITLE
Did you consider codec-jvm?

### ISSUE THREAD

**Issue by minad** [mmhelloworld/idris-jvm#37]
https://github.com/rahulmutt/codec-jvm

**Comment by mmhelloworld** [comment]
Hi,

I did look at `codec-jvm` when I started working on idris-jvm but at that time it had few issues and didn't have support for `invokedynamic`. Now I am actually rewriting idris-jvm with idris-jvm itself porting from Haskell to Idris and compiling to JVM bytecode so we can directly use JVM's `asm` library itself.

**Comment by minad** [comment]
hehe. are you sure thats a good idea, since this will introduce some kind of bootstrapping problem for users?

**Comment by mmhelloworld** [comment]
Only the initial version that I am working on currently needs the Haskell implementation. For the users, we don't need bootstrapping as we can just distribute the idris jvm backend as jar.

**Comment by minad** [comment]
Sure, but bootstrapping means bootstrapping from source ;)

http://bootstrappable.org

**Comment by mmhelloworld** [comment]
That's what I meant too. The current Haskell version will bootstrap the next Idris JVM version and from there on, one idris-jvm version will be used to build the next version. We could still maintain the Haskell version (or write one in Java) so that we can use that to build any version of idris-jvm if that is a concern as mentioned in the link you shared.
