### ISSUE TITLE
Documentation about what is not (yet) possible

### ISSUE THREAD

**Issue by nightscape** [mmhelloworld/idris-jvm#56]
Hi @mmhelloworld,

it would be great if you could add a section to the README about what users should not expect to work (to the best of your knowledge).
Can one interact with arbitrary Java libraries? Would reflection work? Could one write working wrappers for things like Spark? ...
Maybe also with an indication if you already plan to do something, have an idea how to do it or what's open for contributions.

I know this request is a bit vague, but it would give users a clue at what scale one can try out and contribute to idris-jvm.

Thanks a lot!
  Martin

**Comment by mmhelloworld** [comment]
Hi Martin,

> it would be great if you could add a section to the README about what users should not expect to work (to the best of your knowledge).

The things that work are already mentioned in the README and I tend to create Github issues for improvements or for the things that are not there yet (like Java arrays support, annotations support etc).

> Can one interact with arbitrary Java libraries? Would reflection work? Could one write working wrappers for things like Spark? 

To interact with Java libraries, all we need to do is to add FFI declarations. We can call Java methods from Idris and Idris functions can also be exported to Java. Idris can also extend a class and implement interfaces. This has all been mentioned in README. I am not sure what you mean by reflection exactly but if you mean exporting Idris classes for some Java framework like Spring that uses reflection to discover aspects, Idris functions can be exported to Java classes and then they would be just like classes compiled from Java. A big missing piece here is annotations support so that exported classes with Idris implementations can have annotations. I have already started working on this so it should be there soon. As for Spark, I don't have experience with it but as we have FFI support, it should be possible to consume any Java api from Idris.

> Maybe also with an indication if you already plan to do something, have an idea how to do it or what's open for contributions.

The items open for contributions are also Github issues. There are few issues that I have assigned to myself and I will be working on them. The other issues could definitely use some help. Things can be definitely improved here, as you said, I could add some ideas or create some smaller tasks for new contributors and tag them appropriately. I'll try to improve things there going forward.

Thank you!

**Comment by nightscape** [comment]
Hey @mmhelloworld,

if the issue list fully represents what is currently known as not working then that answers my question.
I've been digging through the code a little and must admit that it would take me quite some time to be able to contribute anything really valuable, so maybe my proposal for tagging issues for contributors is not appropriate for something that is essentially still being developed by you alone.

Thank you for creating this great project, I'm hoping to be able to use it in private projects sometime soon!
