### ISSUE TITLE
JvmImport.idr line 8 %dynamic "libc" will not compile on windows.

### ISSUE THREAD

**Issue by alaendle** [mmhelloworld/idris-jvm#81]
Trying to compile the current release fails with the following error message.

`Type checking .\IdrisJvm\JvmImport.idr`
`Uncaught error: user error (Could not load dynamic alternatives "libc")`

As far as I know there isn't a libc implementation on windows. So what is the recommended workaround? Or ist Windows a supported platform any longer?

**Comment by mmhelloworld** [comment]
Hi,

Thank you for reporting. For Windows, you don't have to build idris-jvm from sources. You can use the [releases](https://github.com/mmhelloworld/idris-jvm/releases) directly. With Jvm import, the FFI calls are generated automatically but FFI calls can be made directly without using Jvm import as a workaround. 

`libc` is used to invoke JVM to import Java types so that FFI calls can be generated automatically using Idris type providers. I will look into it if it can be done in a different way without using `libc`.

 I am working on compiling Blodwen for JVM. With that perhaps, we can directly import JVM types as the compiler can be run on the JVM as well.

**Comment by alaendle** [comment]
Hi, I think I've the fix for this - and created a corresponding pull-request. Just let me know what you think ;-)

**Comment by mmhelloworld** [comment]
This is closed via #89. Thank you, @alaendle.
