### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by zvozin** [mmhelloworld/idris-jvm#97]
How to? :)

**Comment by mmhelloworld** [comment]
Hi @zvozin ,

Thank you for your interest in idris-jvm. There are lot of areas where we can improve unsurprisingly :)

* Build tool support - Maven, Gradle etc.
* Libraries - JDBC FFI or high level libraries, Rest client, unit testing, JSON SerDe etc.
* Annotation support to improve Java interop #35. We are already half way on this as idris-jvm supports `String`, enum, array and `int` annotations. We have to complete this one so that an existing Java application can integrate idris-jvm easily and we can also make use of Java libraries and frameworks such as Jackson, Spring Boot, JMH etc.
* Blodwen. This is the area I am focusing on currently to keep up to date with Blodwen so that it can be compiled to JVM and we can run Idris compiler on the JVM one day. 
* And all the other areas where want to use idris-jvm but not well supported at the moment

**Comment by mmhelloworld** [comment]
Idris 2 can now run on the JVM so I will create issues with specific scope for contribution towards Idris 2 on the JVM.
